### ISSUE TITLE
all surveys loaded on each page

### ISSUE THREAD

**Issue by bit** [surveyjs/surveyjs-wordpress#18]
with the plugin installed all pages contain all surveys as a java script variable:

```
<script type='text/javascript'>
/* <![CDATA[ */
var surveys = []
...


```

thats wrong

**Comment by tsv2013** [comment]
I've looked over our code and haven't found the `var surveys = []` srting. I need some time to compose a docker image and check your question.

As far as I remember we don't load all surveys in any page except surveys list and survey results.

**Comment by bit** [comment]
I think its wp_localize_script in https://github.com/surveyjs/surveyjs-wordpress/blob/master/initializer.php#L45

**Comment by tsv2013** [comment]
Thank you for pointing it. We'll check it.

**Comment by dmitrykurmanov** [comment]
reproduced

**Comment by dmitrykurmanov** [comment]
@bit we've fixed the problem. Thank you for the reporting!
