### ISSUE TITLE
Files should be uploaded as file not base64 json

### ISSUE THREAD

**Issue by bit** [surveyjs/surveyjs-wordpress#19]
Using a file input, the form gets submitted as base64 json, but results get cut off at ~ 64kb.

To allow larger file uploads, they should be uploaded via the .onUploadFiles hook.
I.e. by opening up the existing SurveyJS_UploadFile api call or adding another one survey submissions.

**Comment by tsv2013** [comment]
Yes the onUploadFiles is not used in this project. This SurveyJS Wordpress plugin was designed to demonstrate how SurveyJS libraries can be integrated with Wordpress CMS. Some implementations were simplified. And this is enough for most of users.

The SurveyJS Wordpress plugin is an open-source project. You can eleborate is further according your needs. Please take in account that SurveyJS Creator licensing policy - https://surveyjs.io/Licenses#SurveyCreator

**Comment by JaneSjs** [comment]
Hello @bit,
I'm happy to inform you that our developers completed this task: [Upload File Upload question's files to a WordPress storage](https://github.com/surveyjs/surveyjs-wordpress/issues/41). We registered the `survey.onUploadFiles` callback function ([view code](https://github.com/surveyjs/surveyjs-wordpress/blob/237430d2cf46fbd0e0a5d52d4345b2352139d6b2/src/trunk/initializer.php#L225-L250)) to upload files to a specified WordPress storage ([view code](https://github.com/surveyjs/surveyjs-wordpress/blob/237430d2cf46fbd0e0a5d52d4345b2352139d6b2/src/trunk/ajax_handlers/upload_files.php)). Now, the SurveyJS WordPress plugin uploads File question's files to the WordPress file storage directory: `wp-content/surveyjs/`.

Please feel free to contact us if you have any further questions.

Thanks
