### ISSUE TITLE
How can I hook into save results?

### ISSUE THREAD

**Issue by andyg2** [surveyjs/surveyjs-wordpress#24]
I've been trying to use a hook to send an email when the results are saved

`add_action('wp_ajax_SurveyJS_SaveSurvey', 'my_SaveSurvey', 9);`

However it's not firing. 

Currently I'm using this workaround but it's less than ideal.

```
if($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['Json']) && isset($_POST['SurveyId'])) {
  my_SaveSurvey();
}
```

Any help would be appreciated.

**Comment by tsv2013** [comment]
Here is the save results handler code - https://github.com/surveyjs/surveyjs-wordpress/blob/master/src/trunk/ajax_handlers/save_result.php

You can modify it to add your custom functionality

**Comment by andyg2** [comment]
> You can modify it to add your custom functionality

But any modifications would be overwritten when I update the plugin. Would it be possible to add a hook/action in the plugin to remedy this?


    
            function callback() {
                if($_SERVER['REQUEST_METHOD'] === 'POST') {

                    do_action('custom_save_result_handler');

                    global $wpdb;
                    $table_name = $wpdb-&gt;prefix . 'sjs_results';
                    $wpdb->insert( 
                        $table_name, 
                        array( 
                         'surveyId' => intval(sanitize_key($_POST['SurveyId'])),
                         'json' => sanitize_text_field($_POST['Json'])
                        ) 
                    );

                }

            }

**Comment by tsv2013** [comment]
We're not much of Wordpress developers. And we need to learn how the `do_action` method work and what other changes related to it we need to do in our code. We also need to document this hook somehow. Unfortunately right now we don't have spare resources for it. I think we can return to this question after SurveyJS Creator V2 release.

**Comment by andyg2** [comment]
I appreciate the response and I understand how important your time and resources are.

Maybe this helps: adding this line inside the callback would be the absolute extent of the work - there's no other configuration required.

`do_action('anything_here');`

This would allow any developer to call their own code at this point before continuing the normal operation. If there's no actions defined elsewhere, the function has no affect.

I'm perfectly happy to wait until a later version as I have a workaround. I really believe this would be good for your project to allow anyone to decide what to do with the result as it's submitted - it seems like a missing line of code. Action hooks are normally dotted all over wordpress scripts for extensibility - Woocommerce has [1615](https://woocommerce.github.io/code-reference/hooks/hooks.html) of them!!

**Comment by tsv2013** [comment]
Can we pass any parameters for this action, like survey id and JSON in this case?

**Comment by andyg2** [comment]
> Can we pass any parameters for this action, like survey id and JSON in this case?

Yes you can if you want to, in this instance it's not really important as $_POST contains any variable you might need and $_POST will exist in the functions being called - here's both examples.

### With parameters

`do_action( 'example_action', $_POST['SurveyId'], $_POST['Json'] );`

To use this action hook a developer would need to have an `add_action` call with some additional parameters.

`add_action( 'example_action', 'example_callback', 10, 2 );`  where **2** is the number of parameters and 10 is the run priority

...and also the callback function
```
function example_callback( $SurveyId, $Json ){
  // do something with ID and Json
}
```
It's a bit messy in my opinion

### Without parameters it's easier and less to maintain.

`do_action( 'example_action' );`

To use this action hook a developer can use an anonymous function callback for  `add_action` 

```
add_action( 'example_action', function ( ) {
   // do something with $_POST
} );
``` 

Easy :)

**Comment by tsv2013** [comment]
@andyg2 Thank you for the detailed explanations. We'll add this hook in a nearest couple of days.

**Comment by dmitrykurmanov** [comment]
Hello @andyg2,

I am very sorry about the long response. We've added the hook and updated the plugin.

Thanks.
