### ISSUE TITLE
WordPress: Upgrade the SurveyJS library version + Landing Image

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/surveyjs-wordpress#26]
The following issue occurs in SurveyJS Wordpress Plugin: the {CORRECTANSWER} variable is not converted to an actual value. It was reported at [T10786 - {correctAnswer} not work](https://surveyjs.answerdesk.io/internal/ticket/details/T10786).

I believe the issue occurs due to the outdated SurveyJS library version.

**Comment by dmitrykurmanov** [comment]
also need to update main image

![image](https://user-images.githubusercontent.com/22315929/193564137-5b1e9ffa-09c9-44db-bb8d-42c92c3a1514.png)

**Comment by JaneSjs** [comment]
+1 Issue Potentially related to the old version


T11520 - WordPress plugin (SurveyJS Creator v1.8.51) drodpown: all labels cleared when reordering in the Survey view
https://surveyjs.answerdesk.io/internal/ticket/details/T11520

_Using the above, whenever I choose the "Checkbox" widget, set it to dropdown mode, then visually reorder entries in the Survey view (not the property grid), all labels are cleared out._
