### ISSUE TITLE
shortcode documentation

### ISSUE THREAD

**Issue by AndreKelling** [surveyjs/surveyjs-wordpress#3]
in the new gutenberg editor there is no `Add Survey` Button.

Hard to find out the right shortcode, like `[Survey id="1" name="My Grand Survey"]` and add it with the Gutenberg Shortcode Block.

**Comment by tsv2013** [comment]
To be honest SurveyJS shorkcode was not supposed to be inserted manualy.

We are not much of Wordpress users/developers. Could you describe your problem in greater details and provide us with the staps how to reproduce the issue on local developer wordpress instance and we'll be happy to fix it.

**Comment by AndreKelling** [comment]
Yes, it's a plugin for a new kind of editor. 
But will be in **WordPress core** starting approx. 27.11.2018.
To reproduce you can setup a wordpress install the plugin and edit a page or post with gutenberg active.

**Comment by dmitrykurmanov** [comment]
@AndreKelling thanks it is more clear now. We will support it after in will be included in the wordpress core or we will receive more requests here.

**Comment by dmitrykurmanov** [comment]
@AndreKelling we've implemented the Gutenberg editor support.
