### ISSUE TITLE
SurveyJS Creator for Wordpress - Validate Licensing Requirements

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/surveyjs-wordpress#35]
https://github.com/surveyjs/surveyjs-wordpress/blob/065cbb62283483d5bd980fa798c633146a90ca8a/LICENSE#L1

**Comment by ElenaGorbatkova** [comment]
https://github.com/surveyjs/surveyjs-wordpress/pull/36/files
https://github.com/surveyjs/surveyjs-wordpress/pull/38
