### ISSUE TITLE
Survey entries don't show (JSON.parse: bad escaped character)

### ISSUE THREAD

**Issue by kuchengrab** [surveyjs/surveyjs-wordpress#47]
Hi,
when trying to show the results of a [survey](https://rechtaufstadt-forum.de/en/register/) in the Wordpress/SurveyJS backend, it only shows the title and a blank page.
The browser's error log shows the following message:
```
Uncaught SyntaxError: JSON.parse: bad escaped character at line 1 column 280 of the JSON data
    data https://example.com/wp-admin/admin.php?page=surveyjs_results&id=5&name=RaS2024_final_de-en:444
    <anonymous> https://example.com/wp-admin/admin.php?page=surveyjs_results&id=5&name=RaS2024_final_de-en:443
[admin.php:444:41](https://example.com/wp-admin/admin.php?page=surveyjs_results&id=5&name=RaS2024_final_de-en)
``` 
Fortunately, I was able to locate the `wp_sjs_results` table, so I can see the raw JSON data. But I'd like to be able to export the entries as CSV.
Any hints what the "bad escaped character" could be or how to look for it? (I have no clue what "column 280" could mean).

**Comment by JaneSjs** [comment]
Hello @kuchengrab,
The "Uncaught SyntaxError: JSON.parse: bad escaped character at line 1 column 280 of the JSON data," error indicates that there is an issue with the format of the JSON object which is passed to the `JSON.parse()` function.

Unfortunately, it is difficult to determine the cause of the issue using the provided survey form. We would be in a better position to research the issue if you could share an example of a problematic `survey.data` object. You may submit a ticket at [Help Desk](https://surveyjs.answerdesk.io/ticket/list?preset=mytickets) and share relevant data for research.

Thank you

**Comment by kuchengrab** [comment]
Thanks @JaneSjs for your reply. I sent a few lines of the data on the ticket number **T18141**.

**Comment by kuchengrab** [comment]
Ok I did some testing myself and found one problematic JSON data line:
`{\"name\":\"F. \",\"email\":\"example@gmail.com\",\"Einverstaendnis1\":false,\"newsletter\":true,\"ini\":\"ExampleIni\",\"anreise\":\"nein berlin\",\"biete-schlafplatz\":false,\"kinder\":false,\"gesamtes-forum\":\"Ja\",\"unvertr\":false,\"essen-sonst\":\"wird bestimmt lecker &lt;3\&quot;,\&quot;anmerkungen-sonstige\&quot;:\&quot;Wäre sehr gerne dabei &lt;3\&quot;}`
while it should be:
`{\"name\":\"F. \",\"email\":\"example@gmail.com\",\"Einverstaendnis1\":false,\"newsletter\":true,\"ini\":\"ExampleIni\",\"anreise\":\"nein berlin\",\"biete-schlafplatz\":false,\"kinder\":false,\"gesamtes-forum\":\"Ja\",\"unvertr\":false,\"essen-sonst\":\"wird bestimmt lecker <3\",\"anmerkungen-sonstige\":\"Wäre sehr gerne dabei <3\"}`
if I change the database entry manually, the error is gone and the table is rendered correctly.
So the problem seems to be that "<" triggers transformation to html code but also subsequent double quotation marks `"` which is of course unintended. 

To fix my issue for the time being I will need to look through the whole table to find the rest of these errors, I guess ...

**Comment by dmitry-kurmanov** [comment]
We fixed the problem via the https://github.com/surveyjs/surveyjs-wordpress/pull/49. Fix is already available.
