### ISSUE TITLE
Load style in ALL Admin Wordpress

### ISSUE THREAD

**Issue by fpalacioschaves** [surveyjs/surveyjs-wordpress#5]
The plugin changes style in ALL the Wordpress admin. So, to avoid it, you can add this piece of code in initializer.php 
public function enqueue_admin_scripts() {
 if ( isset( $_GET["page"] ) &&
	         ($_GET["page"] == "sjs-settings" ||
	          $_GET['page'] == "sjs-main-menu" ||
	          $_GET['page'] == "surveyjs_editor" ||
	          $_GET['page'] == "surveyjs_results"
	         )
	    ) {
... (all css and jquery files)
}
}

**Comment by tsv2013** [comment]
@fpalacioschaves Thank you for the valueable info. We'll fix it ASAP.

**Comment by fpalacioschaves** [comment]
Cool. You're welcome
