### ISSUE TITLE
Form doesn't store submissions after adding expression currentDate()

### ISSUE THREAD

**Issue by kuchengrab** [surveyjs/surveyjs-wordpress#50]
Hi,
sorry for submitting yet another issue. After fiddleing about with the timestamp thing (#48 / [this comment](https://github.com/surveyjs/surveyjs-wordpress/issues/47#issuecomment-2109001333)), which I implemented semi-successfully with the expression `currentDate()`, my form stopped storing any submissions to the database altogether (other forms still worked fine).
I tried debugging it for a few hours — deleting the expression, copying the form, testing different browsers and devices. I couldn't get it to work again, though. The worst thing is that you didn't get a clue as a user, that your entry wasn't saved (no error message, nothing).
Trying this out on a live site in the middle of our conference registration phase running was a bad idea, obviously, but ... I also lost my confidence in the SurveyJS wordpress plugin at that point. 😞 
In the end I spent the night recreating the form with ninjaforms. Now it's ugly, but it works again. Plus I have the automatic email functionality (= feature suggestion) that is great to give participants instant feedback as well as for backup, in case the stored submissions become corrupted.
To end this on a less anecdotal note: Here is my form JSON, if you'd like to have a look at it to see whether you can recreate the bug: [ras24-survey.json](https://github.com/surveyjs/surveyjs-wordpress/files/15313833/ras24-survey.json)

Best, kuchengrab

**Comment by JaneSjs** [comment]
Hello @kuchengrab,
I apologies for missing your inquiry. I regret to hear that your form failed to run during the conference.

Thank you for sharing a survey JSON definiton. I tested it on my end ([View Plunker](https://plnkr.co/edit/HKF22AOmQXWJKyul)) and confirmed that the expression appears correctly:
![image](https://github.com/user-attachments/assets/c9bb31c5-1219-4274-af4d-ae31adccc938)

However, we may need to additionally check it on WordPress. I'll reach out to our developers for further clarification.
Meanwhile, would you please elaborate on the issue? Please clarify whether you couldn't save the entire form response or this particular expression field with the `currentDate()` function?

For the record: for bugreports, please feel free to [submit a ticket at help desk](https://surveyjs.answerdesk.io/ticket/list?preset=mytickets&_gl=1*1nc779q*_gcl_au*MTcyNTMyNTUzMi4xNzIyMDg4MzA0LjE1MDk3NDc4OC4xNzI0NjYzNTc5LjE3MjQ2NjM1Nzg.*_ga*MTQxMjcxNzA2OS4xNzE1NjA2ODM5*_ga_SM5CHDPRR8*MTcyNDY2NTMyNi4xMDQuMS4xNzI0NjY4Mjk0LjAuMS4xNzgwNDg5NDg3).

**Comment by JaneSjs** [comment]
Hello @kuchengrab,
We tried your JSON on our end, however, didn't reproduce the issue on our end. Form results were successfully saved to a database.

We may recommend that you create a new survey and apply the target layout without further modifications such as adding/removing questions.

Thanks
