### ISSUE TITLE
Single-Line Input: Quotation marks in a value cause an error

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/surveyjs-wordpress#59]
T20766 - JSON error – handling of quotes in text comments
https://surveyjs.answerdesk.io/internal/ticket/details/T20766

**Comment by dmitry-kurmanov** [comment]
Supported Use-Cases:

![image](https://github.com/user-attachments/assets/f7b26cc3-1932-467d-8ce3-1cf7a6aa5a72)
