### ISSUE TITLE
very long surveys issue

### ISSUE THREAD

**Issue by javaseth** [surveyjs/surveyjs-wordpress#9]
We built an ISO9001 assessment survey and it was like 170 kb. The MySQL table (sjs_my_surveys) field (json) for the survey json file is of type TEXT, which is maximum 64K. 
The result was that the survey was impossible to save on WP.
Maybe the field should be of type MEDIUMTEXT, this was our workaround (ALTER sjs_my_surveys TABLE)

**Comment by tsv2013** [comment]
I'll implement this next week. Please ping me in a week if I forget.

**Comment by dmitrykurmanov** [comment]
@javaseth  thank you for the interest. We've implemented this enhancement.
